### ISSUE TITLE
Consolidate existing high-value data standards and metadata fields to integrate them and publish authoritative standards

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#107]
- [ ] Pacific Salmon Explorer for standard CU fields, stock-recruit and return data
- [ ] WSP Rapid assessment data
- [ ] PSSI Business Glossary in Purview
- [ ] Keywords in Pacific Salmon Data Portal (same as business glossary?)
- [ ] [NuSEDS-New Salmon Escapement Database System - Open Government Portal](https://open.canada.ca/data/en/dataset/c48669a3-045b-400d-b730-48aafe8c5ee6)
- [ ] [Pacific Salmon Conservation Units, Sites & Status - Open Government Portal](https://open.canada.ca/data/dataset/1ac00a39-4770-443d-8a6b-9656c06df6a3)
- [ ] [Pacific Salmon Stock Management Units - Open Government Portal](https://open.canada.ca/data/en/dataset/776a7aa3-a265-4f13-827c-eb2ef1ac2889)
